### ISSUE TITLE
Unix line endings changed to Windows line endings

### ISSUE THREAD

**Issue by jensli** [grosenberg/fluentmark#15]
When I open a file with Unix line ending those a immediately changed to windows line endings.

This changes the opened file, which becomes dirty (displaying a '*' symbol in the editor tab header in Eclipse). This is before any manually edits has been performed to the editor.

**Comment by grosenberg** [comment]
This is a platform setting. Nothing in Fluentmark that modifies the editor line ending.

**Comment by jensli** [comment]
> This is a platform setting. Nothing in Fluentmark that modifies the editor line ending.

Hm. I think that is the case. It doesn't happen with any other kind of editor, including the standard Eclipse text editor and the Wiki-text markdown editor.

Are you positive that you have opened a file with Unix line delimiters in FluentMark without having this happen?

An easy way to reproduce in Eclipse is this:

* Enable display of whitespace characters: *Preferences* -> *Show whitespace characters (configure visibility)*.
* Check *Linefeed* and *Carriage return* in *Trailing* column.
* Select a file in *Package Explorer* and run command  *File* -> *Convert Line Delimiters To* -> *Unix*.
* Open file in FluentMark.
* Check the number of characters at the end of each line. 2 = Windows, 1 = Unix.

Every time I do this with FluentMark endings are changed to two characters. Every time I do this with any other editor the line endings are preserved.

Maybe this is only triggered when running on Windows. Maybe it is the other way around on a Unix.

Software versions:
* Windows 10 
* Eclipse Neon.2 Release (4.6.2)
* Java 1.8.0_131
* FluentMark 0.9.1

**Comment by jensli** [comment]
May guess is that when FluentMark reads and renders a file then the existing line ending is somehow replaced by `System.lineSeparator()`.

**Comment by jensli** [comment]
It seems like the editor is doing hard line wrapping when the user enters text. Maybe the bug is related to that functionality.

**Comment by bassenj** [comment]
I see the same behaviour on

 - Window 10
 - Eclipse 4.10.0
 - Java 1.8.0_201-b09
 - FluentMark 1.2.0

My platform setting is
`Window > Preferences > General > Workspace > New text file line delimiter = Unix`

Is there any fix for this behaviour?

**Comment by iona5** [comment]
can confirm that this still happens and its directly related with the FluentMark Editor - which otherwise i think is really a great tool! :) .

Steps To Reproduce: 
**Environment:**
_Windows 10
Eclipse 2019-03 (4.11.0)
FluentMark Editor 1.2.0.20180807-2118)_

1. Create an empty, generic project in your workspace
2. make sure "Unix" Line Endings are enabled (Project -> Properties -> Resource -> "New text file line delimiter")
3. create new Markdown file (File -> New -> Other...) => Certiv Tools -> FluentMark file
4. enter Return at the end of the existing line `#FluentMark`
5. make sure whitespace characters are shown (Window -> Editor -> "Show Whitespace Characters")
6. verify there's only a single LF character (the "flipped P") at the end of the line
7. save and close file
8. open file again with "FluentMark Editor"

EXPECTED:
there is only the LF character and file is not modified
ACTUAL:
now the end of the line is CRLF ("star" + "flipped P") and the file shows modified marker (asterisk in tab)

ADDITIONAL INFORMATION:
opening the file with "Text Editor" does not change the EOL character

This is pretty annoying. If this is a platform setting, can somebody please point me to where i can change that?

**Comment by rplanaatnc** [comment]
Is there an update to this? The issue is marked "Closed" and yet the bug still exists in the version that I just installed (net.certive.fluentmark_1.2.0.20180807-2118). Where can I find the fix?
