### ISSUE TITLE
Remove support for legacy converters.

### ISSUE THREAD

**Issue by grosenberg** [grosenberg/fluentmark#30]
Proposal is to remove support for the CommonMark, MarkdownJ, Pegdown & TxtMark converters from Fluentmark.

Pandoc is the currently preferred markdown converter.  Pandoc is actively developed & supported. Not clear if the other converters are as widely used.

If there are reasons to retain any of the legacy converters, please explain in a comment.

**Comment by JanecekPetr** [comment]
Obviously, pandoc is nice because it [supports CommonMark](https://pandoc.org/MANUAL.html#markdown-variants), too.

The only issue with it is that it must be installed.

On the other hand, [the Java implementation of CommonMark from Atlassian](https://github.com/atlassian/commonmark-java) is still actively developed and supported, too, and does not need any external installation. Having that engine in the plugin would be a nice fallback for users who do not want to install pandoc (yet).
